// ─── CONFIG ───────────────────────────────────────────────────────────────────
export const TELEGRAM_BOT_TOKEN = "YOUR_BOT_TOKEN_HERE";
export const TELEGRAM_CHAT_ID = "YOUR_CHAT_ID_HERE";

// ─── TRANSLATIONS ─────────────────────────────────────────────────────────────
export const translations = {
    ru: {
        nav: {
            about: "О сервисе",
            services: "Услуги",
            reviews: "Отзывы",
            contacts: "Контакты",
            cta: "Записаться",
        },
        hero: {
            badge: "Профессиональный авто сервис",
            title: "Надёжный ремонт и обслуживание автомобилей в Молдове",
            description:
                "Диагностика, ремонт кондиционеров и полное техническое обслуживание вашего автомобиля. Работаем быстро, честно и качественно.",
            ctaPrimary: "Записаться на приём",
            ctaSecondary: "Узнать подробнее",
            stat1: "лет опыта",
            stat2: "клиентов",
            stat3: "марок авто",
            brandsTitle: "Работаем с ведущими брендами",
        },
        about: {
            sectionTag: "О нас",
            title: "Ваш автомобиль —",
            titleAccent: "в надёжных руках",
            p1: "REF-Service — современный автосервис, где каждый автомобиль получает профессиональный уход. Мы используем только оригинальные запчасти и передовое диагностическое оборудование.",
            p2: "Наша команда сертифицированных специалистов решает задачи любой сложности — от планового ТО до капитального ремонта. Мы ценим ваше время и всегда держим вас в курсе происходящего.",
            feature1Title: "Современное оборудование",
            feature1Desc: "Профессиональные стенды и диагностика",
            feature2Title: "Быстрое обслуживание",
            feature2Desc: "Готовый результат в кратчайшие сроки",
            feature3Title: "Оригинальные запчасти",
            feature3Desc: "Только проверенные поставщики",
        },
        services: {
            sectionTag: "Услуги",
            title: "Что мы",
            titleAccent: "делаем",
            acTitle: "Ремонт и обслуживание кондиционеров",
            acDesc: "Полный спектр услуг по диагностике, заправке и ремонту автомобильных климатических систем. Работаем со всеми марками и моделями авто.",
            acFeatures: [
                "Диагностика системы кондиционирования",
                "Заправка фреоном R134a / R1234yf",
                "Замена компрессора и фильтра",
                "Дезинфекция и чистка системы",
                "Ремонт испарителя и конденсатора",
                "Проверка на утечки",
            ],
            acCta: "Записаться",
        },
        reviews: {
            sectionTag: "Отзывы",
            title: "Что говорят",
            titleAccent: "клиенты",
            items: [
                {
                    name: "Александр М.",
                    car: "Toyota Camry",
                    text: "Отличный сервис! Сделали диагностику и заправили кондиционер за 2 часа. Цены честные, мастера объяснили всё подробно. Буду обращаться ещё.",
                    rating: 5,
                },
                {
                    name: "Елена В.",
                    car: "Volkswagen Passat",
                    text: "Очень довольна работой. Кондиционер не холодил — нашли утечку, починили и заправили. Всё работает как новое. Рекомендую всем знакомым!",
                    rating: 5,
                },
                {
                    name: "Дмитрий К.",
                    car: "BMW 3 Series",
                    text: "Профессиональный подход, чистота в боксах, вежливый персонал. Сделали всё быстро и качественно. Отдельное спасибо за честность с ценами.",
                    rating: 5,
                },
                {
                    name: "Ирина С.",
                    car: "Ford Focus",
                    text: "Обратилась по рекомендации — не пожалела. Заменили компрессор кондиционера, дали гарантию 6 месяцев. Уже езжу второй сезон — всё отлично!",
                    rating: 5,
                },
            ],
        },
        contacts: {
            sectionTag: "Контакты",
            title: "Как нас",
            titleAccent: "найти",
            address: "str. Traian 8, MD-3100, Bălți",
            phone: "+373 692 91 979",
            email: "info@ref-service.md",
            hours: "Пн–Пт: 8:00–18:00 | Сб: 8:00–16:00",
            ctaTitle: "Запишитесь онлайн",
            ctaDesc: "Оставьте заявку и мы свяжемся с вами в течение 30 минут",
            namePlaceholder: "Ваше имя",
            phonePlaceholder: "Номер телефона",
            messagePlaceholder: "Опишите проблему (необязательно)",
            submitBtn: "Отправить заявку",
            loadingBtn: "Отправка...",
            successMsg: "Спасибо! Мы свяжемся с вами скоро.",
            errorMsg: "Ошибка отправки. Попробуйте позже.",
        },
        footer: {
            tagline: "Профессиональный авто сервис",
            rights: "Все права защищены",
            navTitle: "Навигация",
            workTitle: "Режим работы",
            workDays: "Понедельник – Пятница",
            workDaysHours: "8:00 – 18:00",
            workSat: "Суббота",
            workSatHours: "8:00 – 16:00",
            workSun: "Воскресенье",
            workSunHours: "Выходной",
        },
    },
    ro: {
        nav: {
            about: "Despre noi",
            services: "Servicii",
            reviews: "Recenzii",
            contacts: "Contacte",
            cta: "Programare",
        },
        hero: {
            badge: "Service auto profesional",
            title: "Reparații și întreținere auto de încredere în Moldova",
            description:
                "Diagnosticare, reparații climatizare și service complet pentru vehiculul tău. Lucrăm rapid, cinstit și calitativ.",
            ctaPrimary: "Programează-te",
            ctaSecondary: "Află mai mult",
            stat1: "ani experiență",
            stat2: "clienți",
            stat3: "mărci auto",
            brandsTitle: "Lucrăm cu branduri de top",
        },
        about: {
            sectionTag: "Despre noi",
            title: "Mașina ta —",
            titleAccent: "pe mâini bune",
            p1: "REF-Service este un service auto modern, unde fiecare vehicul primește îngrijire profesională. Folosim doar piese originale și echipamente de diagnosticare de ultimă generație.",
            p2: "Echipa noastră de specialiști certificați rezolvă sarcini de orice complexitate — de la inspecții tehnice planificate la reparații capitale. Respectăm timpul tău și te ținem mereu la curent.",
            feature1Title: "Echipament modern",
            feature1Desc: "Standuri profesionale și diagnosticare",
            feature2Title: "Serviciu rapid",
            feature2Desc: "Rezultat gata în timp minim",
            feature3Title: "Piese originale",
            feature3Desc: "Doar furnizori verificați",
        },
        services: {
            sectionTag: "Servicii",
            title: "Ce",
            titleAccent: "oferim",
            acTitle: "Reparație și întreținere climatizare",
            acDesc: "Gamă completă de servicii pentru diagnosticarea, încărcarea și repararea sistemelor de climatizare auto. Lucrăm cu toate mărcile și modelele.",
            acFeatures: [
                "Diagnosticarea sistemului de climatizare",
                "Încărcare freon R134a / R1234yf",
                "Înlocuire compresor și filtru",
                "Dezinfecție și curățare sistem",
                "Reparație evaporator și condensator",
                "Verificare scurgeri",
            ],
            acCta: "Programare",
        },
        reviews: {
            sectionTag: "Recenzii",
            title: "Ce spun",
            titleAccent: "clienții",
            items: [
                {
                    name: "Alexandru M.",
                    car: "Toyota Camry",
                    text: "Service excelent! Au făcut diagnosticarea și încărcarea climatizării în 2 ore. Prețuri corecte, mecanicii au explicat totul în detaliu. Voi reveni cu siguranță.",
                    rating: 5,
                },
                {
                    name: "Elena V.",
                    car: "Volkswagen Passat",
                    text: "Foarte mulțumită de lucrare. Climatizarea nu răcea — au găsit scurgerea, reparat și reîncărcat. Totul funcționează ca nou. Recomand tuturor!",
                    rating: 5,
                },
                {
                    name: "Dmitri K.",
                    car: "BMW 3 Series",
                    text: "Abordare profesională, curățenie în boxe, personal amabil. Au lucrat rapid și calitativ. Mulțumiri speciale pentru corectitudinea prețurilor.",
                    rating: 5,
                },
                {
                    name: "Irina S.",
                    car: "Ford Focus",
                    text: "Am venit la recomandare — nu m-am căit. Au înlocuit compresorul, garanție 6 luni. Conduc deja al doilea sezon — totul perfect!",
                    rating: 5,
                },
            ],
        },
        contacts: {
            sectionTag: "Contacte",
            title: "Cum să ne",
            titleAccent: "găsiți",
            address: "str. Traian 8, MD-3100, Bălți",
            phone: "+373 692 91 979",
            email: "info@ref-service.md",
            hours: "Lun–Vin: 8:00–18:00 | Sâm: 8:00–16:00",
            ctaTitle: "Programați-vă online",
            ctaDesc: "Lăsați o cerere și vă vom contacta în 30 de minute",
            namePlaceholder: "Numele dvs.",
            phonePlaceholder: "Număr de telefon",
            messagePlaceholder: "Descrieți problema (opțional)",
            submitBtn: "Trimite cererea",
            loadingBtn: "Se trimite...",
            successMsg: "Mulțumim! Vă vom contacta în curând.",
            errorMsg: "Eroare la trimitere. Încercați mai târziu.",
        },
        footer: {
            tagline: "Service auto profesional",
            rights: "Toate drepturile rezervate",
            navTitle: "Navigare",
            workTitle: "Program de lucru",
            workDays: "Luni – Vineri",
            workDaysHours: "8:00 – 18:00",
            workSat: "Sâmbătă",
            workSatHours: "8:00 – 16:00",
            workSun: "Duminică",
            workSunHours: "Zi liberă",
        },
    },
};

// ─── STATIC DATA ──────────────────────────────────────────────────────────────
export const BRANDS = [
    { name: "Carrier", src: "./carrier.png" },
    { name: "Eberspächer", src: "./eberspacher.png" },
    { name: "Thermo King", src: "./thermoking.png" },
    { name: "Webasto", src: "./webasto.png" },
];

export const GALLERY_SLIDES = [
    {
        src: "https://images.unsplash.com/photo-1625047509248-ec889cbff17f?q=80&w=800&auto=format&fit=crop",
    },
    {
        src: "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?q=80&w=800&auto=format&fit=crop",
    },
    {
        src: "https://images.unsplash.com/photo-1487754180451-c456f719a1fc?q=80&w=800&auto=format&fit=crop",
    },
    {
        src: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?q=80&w=800&auto=format&fit=crop",
    },
];
