name: Deploy React App to GitHub Pages

on:
    push:
        branches:
            - main

permissions:
    contents: write

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        environment: github-pages

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "npm"

            - name: Install dependencies
              run: npm install

            - name: Build project
              run: npm run build

              env:
                  REACT_APP_TELEGRAM_BOT_ID: ${{ secrets.REACT_APP_TELEGRAM_BOT_ID }}
                  REACT_APP_TELEGRAM_BOT_TOKEN: ${{ secrets.REACT_APP_TELEGRAM_BOT_TOKEN }}

            - name: Deploy to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  folder: build
                  branch: gh-pages
